#!/bin/bash

output_file="report.html"

generate_report() {
    {
        echo "<HTML>"
        echo "<HEAD>"
        echo "<TITLE>System Information Report For $(hostname)</TITLE>"
        echo "</HEAD>"
        echo "<BODY>"
        echo "<H1>System Information Report For $(hostname)</H1>"
        echo "<P>Generated $(date), by $(whoami)</P>"
        echo "<H2>System Uptime</H2>"
        echo "<PRE>$(uptime)</PRE>"
        echo "<H2>Disk Space Utilization</H2>"
        echo "<PRE>$(df -h)</PRE>"

        report_home_space

        echo "</BODY>"
        echo "</HTML>"
    } | tee $output_file
}

report_home_space() {
    local format="%8s%10s%10s\n"
    local i dir_list total_files total_dirs total_size user_name
    if [[ $(id -u) -eq 0 ]]; then
        dir_list=/home/*
        user_name="All Users"
    else
        dir_list=$HOME
        user_name=$USER
    fi
    echo "<H2>Home Space Utilization ($user_name)</H2>"
    for i in $dir_list; do
        total_files=$(find $i -type f | wc -l)
        total_dirs=$(find $i -type d | wc -l)
        total_size=$(du -sh $i | cut -f 1)
        echo "<H3>$i</H3>"
        echo "<PRE>"
        printf "$format" "Dirs" "Files" "Size"
        printf "$format" "----" "-----" "----"
        printf "$format" $total_dirs $total_files $total_size
        echo "</PRE>"
    done
}

generate_uptime_report() {
    {
        echo "<HTML>"
        echo "<HEAD>"
        echo "<TITLE>System Uptime Report For $(hostname)</TITLE>"
        echo "</HEAD>"
        echo "<BODY>"
        echo "<H1>System Uptime Report For $(hostname)</H1>"
        echo "<P>Generated $(date), by $(whoami)</P>"
        echo "<H2>System Uptime</H2>"
        echo "<PRE>$(uptime)</PRE>"
        echo "</BODY>"
        echo "</HTML>"
    } | tee uptime_report.html
}

generate_disk_space_report() {
    {
        echo "<HTML>"
        echo "<HEAD>"
        echo "<TITLE>Disk Space Utilization Report For $(hostname)</TITLE>"
        echo "</HEAD>"
        echo "<BODY>"
        echo "<H1>Disk Space Utilization Report For $(hostname)</H1>"
        echo "<P>Generated $(date), by $(whoami)</P>"
        echo "<H2>Disk Space Utilization</H2>"
        echo "<PRE>$(df -h)</PRE>"
        echo "</BODY>"
        echo "</HTML>"
    } | tee disk_space_report.html
}

generate_home_space_report() {
    {
        echo "<HTML>"
        echo "<HEAD>"
        echo "<TITLE>Home Space Utilization Report For $(hostname)</TITLE>"
        echo "</HEAD>"
        echo "<BODY>"
        echo "<H1>Home Space Utilization Report For $(hostname)</H1>"
        echo "<P>Generated $(date), by $(whoami)</P>"
        report_home_space
        echo "</BODY>"
        echo "</HTML>"
    } | tee home_space_report.html
}

# Основной цикл
while true; do
    choice=$(zenity --list --title="Выберите функцию" --column="Функция" "Сгенерировать полный отчет" "Отчет о времени работы системы" "Отчет о дисковом пространстве" "Отчет о домашнем пространстве" "Выход")

    case $choice in
        "Сгенерировать полный отчет")
            generate_report 2>/dev/null
            xdg-open $output_file
            ;;
        "Отчет о времени работы системы")
            generate_uptime_report 2>/dev/null
            xdg-open uptime_report.html
            ;;
        "Отчет о дисковом пространстве")
            generate_disk_space_report 2>/dev/null
            xdg-open disk_space_report.html
            ;;
        "Отчет о домашнем пространстве")
            generate_home_space_report 2>/dev/null
            xdg-open home_space_report.html
            ;;
        "Выход")
            break
            ;;
        *)
            zenity --error --text="Неизвестный выбор"
            ;;
    esac
done

